### PR TITLE
Structural Changes for Scaling Up, New Landing Page.

### PR DESCRIPTION
**Pull request by tkyler**
2 commits.  First one proposes a new landing page, (introduction) and moved the previous landing page and its screenshots,  'index.md -> now features.md'.   This change was made to accomodate differing visitor cognitive states,  "Developers, Admins and Laymen  endusers are all differing cognitive patterns of thought".  The new landing page is short and visitors can very quickly go to the part of the site they need to.  We should anticipate "grandma, and non-technical folks" seeing this page and we want to get them to the User guide as quickly as possible without them having to hunt for it and get frustrated.  IT/Devs/Admins are smart enough to know where to go.  Oh..I also added the glightbox plugin entry...so folks can click on images and get 'big versions'.  Try it on the main landing page.

image

The 2nd commit simply reorganizes many of the markdown files into sub folders, with no real change in content to any of the markdown files or existing nav structure beyond the first commit.  This was mostly a YML nav section change and movement of files.  This is simply a structural change in order to mimic the navigation scheme of the site.  The main purpose is to anticipate scaling up with screenshots and we want the screenshots to be in the same logical folders as their source markdown.  The 'docs' folder was getting a little long in it 'flat' format, which is confusing to navigate from a dev point of view.  Its like cooking in a messy kitchen.  Finally, I altered some filenames for consistent lower-case naming conventions.  

image

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Thanks a lot, great ideas!

Just some minor points to consider for the landing page:

- When the page was still quite long, the DigitalOcean logo was only visible on scrolling down. Now I feel it gets way to much visibility, given that DO is only giving us a discount for the cdemo hosting, and also the "thanks" is a bit too strong now. Can we tone it down? Perhaps we can move the logo to a credits page or something.
- I suggest to make the "Want to try a demo" a paragraph, not a bullet point
- I am not a big fan of links starting with "click here" - can we avoid it?
- Can we mention on the landing page that it it also works on mobile?

Let me know if you disagree.

In general (not needed in this PR), I think we should think about a new landing page screenshot. Perhaps we can use a mobile screenshot, because it will be much more readable and will convey the suitability for mobile without words. Examples: https://www.photoprism.app/, https://www.home-assistant.io/

**Comment by tkyler** [comment]
Those are all fine recommendations David,  I'm coming in a bit blind so was expecting a few changes.  I've implemented all those suggestions.

image

I moved the Digital Ocean logo to the page regarding installation using the Digital Ocean 1-click, it seems like a logical place for it.

I'm still a complete PR workflow newbie though and will have to do some homework on how to update changes without creating headaches for others.  Since submitting this PR, I have completely rewritten the User Guide on another local branch, and unsure how to get those changes submitted for review and how it relates to this PR.    I apologize in advance if I make a mess while learning this stuff.

**Comment by DavidMStraub** [comment]
If it's possible to separate the changes into several PRs, that would simplify merging, i.e. not adding all of the other changes but only updating the existing branch. Do you think you'll manage?

**Comment by tkyler** [comment]
I pushed the small update I made to the main page per your comments here (reflected in the screenshot above) and will not add to this PR further.  That keeps this PR simple and easy to merge should you wish to do so.

Beyond this PR, I will continue to work on my User Guide rewrite on my own fork. Once I complete my version of the User Guide, my focus will shift to using it to train my family on the use of Gramps Web and I will not be concerned with whether or how the work is merged with the main branch.  That is a decision for others to make.

In the spirit of Open Source however, I fully want the work to be available to the community and so I will publish my version of the docs to a 'review URL' and provide  a link such that you may review the work it in context.  Then, if you decide you would like to integrate any part of it, you can cherry pick elements  from my fork at your leisure and integrate them in a way that is comfortable to you and on your own timing, rather than risking me submitting confusing PRs.

**Comment by DavidMStraub** [comment]
Thank you! It would still be great if you could keep me up to date about progress on your fork, so I can cherry-pick.

**Comment by DavidMStraub** [comment]
@tkyler, unfortunately after merging the PR the pages don't build successfully anymore:

```
ERROR   -  Config value 'plugins': The "glightbox" plugin is not installed
```

It would be great if you could help me find out how to make it work again.

**Comment by DavidMStraub** [comment]
Never mind, I got it to work!

**Comment by DavidMStraub** [comment]
Unfortunately, I realized a huge number of links are broken on grampsweb.org now. I managed to fix some of them, but I have to go to bed now. If you can help out fixing some more, that would be welcome. I didn't check properly before merging unfortunately.

**Pull request merged**
